### ISSUE TITLE
MongoPagination

### ISSUE THREAD

**Issue by L-Luciano** [algoan/nestjs-components#112]
Hello,

The sort field in MongoPagination is an array whereas to request a sort in mongo, it's a Object|String field.

https://mongoosejs.com/docs/api.html#query_Query-sort

Is it possible to change this ?

Regards

**Comment by ccoeurderoy** [comment]
Hello @L-Luciano! 

I'm sorry for the late answer... Well I agree, a sort (or a project) should be an object, and I can't remember why we've chosen an array 🤔 

Honestly, It has more sense to change this as an Object|String, what do you think @na-ji and @meriamBenSassi?

**Comment by L-Luciano** [comment]
No worry but do you think you'll fix it soon ?

**Comment by meriamBenSassi** [comment]
Yes I think it was a mistake. We will fix it soon
