### ISSUE TITLE
Which message pattern does the Pub/Sub library expose for effective routing

### ISSUE THREAD

**Issue by kylehouston** [algoan/nestjs-components#264]
When using the NestJS hybrid approach what transport do we add to the `@MessagePattern` to ensure the events get routed to the correct callback?

`export declare const MessagePattern: <T = string | PatternMetadata>(metadata?: T, transport?: Transport) => MethodDecorator;
`
```
@MessagePattern('test-topic', ???)
  async handlePubSubMessage(payload: any) {
    console.log(`Pub/Sub ----> ${JSON.stringify(payload)} created`);
  }
```

**Comment by kylehouston** [comment]
Looks like GCPPubSubServer Class needs to expose a transportId similar to https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-redis.ts#L24

**Comment by ccoeurderoy** [comment]
Hey @kylehouston, that is a good question! And yes you are right, we should add the `transportId` property to this class. However, according to the [`CustomTransportStrategy`](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/microservices/interfaces/custom-transport-strategy.interface.ts), it expects a value from the `Transport` enum 😕 

It might be interesting to ask the question to the Nest Discord channel in order to know how we could handle hybrid applications with a custom microservice.

**Comment by kylehouston** [comment]
Thanks @ccoeurderoy - yeah the `CustomTransportStrategy` expecting the `Transport` enum was the bit that has me concerned. Out of interest, how would you hack this?

I'll reach out in the Discord for sure and see where things go!

**Comment by ccoeurderoy** [comment]
> Out of interest, how would you hack this? 

I could disable the TS check with a dirty `// @ts-ignore` since there is a condition on `transportId` [here](https://github.com/nestjs/nest/blob/72a88d5e76d940cf5b7e962d16dcfa999e283a8f/packages/microservices/listeners-controller.ts#L71):

```ts
  /**
   * Transport ID required to bind transport when using hybrid applications
   */
  // @ts-ignore
  public readonly transportId: number = 100;
``` 

But I don't like that honestly 😅

**Comment by ccoeurderoy** [comment]
I'll keep this issue open until Nest provides a clean answer

**Comment by kylehouston** [comment]
Thanks @ccoeurderoy, looking again at the MessagePattern, there's a param for metadata - is there anything in the pub/sub library options I could use?

`export declare const MessagePattern: <T = string | PatternMetadata>(metadata?: T, transport?: Transport) => MethodDecorator;`

Logged a message in the support channel, hopefully someone will come back with a nice way to make this work :)

**Comment by ccoeurderoy** [comment]
> is there anything in the pub/sub library options I could use?

Well, honestly I don't know since this signature has never been mentioned in the Nest documentation (sorry for the late answer)

By the way, did you get an answer from Discord?

**Comment by kylehouston** [comment]
No worries @ccoeurderoy - no reply in discord :/ I'll try following up, doesn't make sense that a custom strategy transport id should be a list of known nestjs enums

**Comment by ccoeurderoy** [comment]
Hey @kylehouston, looks like it has been added to Nest since v8.3.0 (see this [pull request](https://github.com/nestjs/nest/pull/8933) 🥳
