### ISSUE TITLE
Conflicting dependencies and peer dependencies

### ISSUE THREAD

**Issue by dfernandesbsolus** [algoan/nestjs-components#362]
Hi Guys, there is a conflict between dependencies and peer dependencies of @nestjs.

Is this on purpose?

![image](https://user-images.githubusercontent.com/96054351/148218717-2a64062b-f2ff-4f91-b35b-84ab7493524f.png)

**Comment by ccoeurderoy** [comment]
Hi @dfernandesbsolus, thank you for noticing this! It seems to be a mistake, could you please tell me on which package did you notice this?

**Comment by dfernandesbsolus** [comment]
> Hi @dfernandesbsolus, thank you for noticing this! It seems to be a mistake, could you please tell me on which package did you notice this?

Hi @ccoeurderoy sorry I forgot to say this.

This error is in the nestjs-pagination

![image](https://user-images.githubusercontent.com/96054351/148221172-1a2506b4-587d-44af-b593-b1e117a8559c.png)

**Comment by ccoeurderoy** [comment]
Indeed, the `nestjs-pagination` package-lock file does not fit the `package.json` file and we need to correct this

**Comment by ccoeurderoy** [comment]
Should be resolved [here](#351), but I'm facing some issues with lerna

**Comment by dfernandesbsolus** [comment]
@ccoeurderoy Unfortunately i don't know Lerna to help you :D

Merci for your work.

**Comment by ccoeurderoy** [comment]
Hey @dfernandesbsolus, we've just released the [v5.0.4](https://github.com/algoan/nestjs-components/releases/tag/%40algoan%2Fnestjs-pagination%405.0.4) and I hope it will fix the peer dependency issue!

Feel free to re-open this issue if it does not work 🚀
