### ISSUE TITLE
(chore) improve the `repository` entry on `package.json` to follow the monorepo structure

### ISSUE THREAD

**Issue by micalevisk** [algoan/nestjs-components#411]
For instance, if you change this:

https://github.com/algoan/nestjs-components/blob/f58e1812b9e1d9b55e54321b47e146fd8f330e44/packages/pagination/package.json#L13-L16

to this:

```
  "repository": {
    "url": "https://github.com/algoan/nestjs-components",
    "directory": "packages/pagination"
  },
```

then the _repository_ link on NPM website will bring us to the `./packages/pagination` dir instead of the root of the project

**Comment by ccoeurderoy** [comment]
Hey @micalevisk, thank you for your suggestion! Indeed, this is will be better on npm
