### ISSUE TITLE
How to set the deadLetterPolicy

### ISSUE THREAD

**Issue by Bamorem** [algoan/nestjs-components#515]
I would like to know how to set the deadLetterPolicy for the subscriptions ?

I didn't found it in the doc. we can see that there is the option inside '@google-cloud/pubsub/build/src/pubsub'.

you can see in the google docs : https://googleapis.dev/nodejs/pubsub/latest/google.pubsub.v1.DeadLetterPolicy.html

and a concrete example here : https://deliveryhero.github.io/hfc-pubsub/subscribing/dead-letter-policy

but i don't see how to do it from : 

strategy: new GCPubSubServer({...})

can you help me ?

**Comment by Bamorem** [comment]
I think i find something but it return me an error.

`new GCPubSubServer({
      listenOptions: {
        autoAck: false,
        subscriptionOptions: {
          create: {
            deadLetterPolicy: {
              deadLetterTopic: 'dead_letter',
              maxDeliveryAttempts: 5,
              createDefaultSubscription: true,
            },
          },
        },
      },
      projectId: `projectId`
    })`
    
    But buy doing this I get this error
    
    `(node:26381) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Invalid resource name given (dead_letter_topic=dead_letter). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.
    at Object.callErrorFromStatus (/Users/Sites/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/Sites/node_modules/@grpc/grpc-js/src/client.ts:351:36)
    at Object.onReceiveStatus (/Users/Sites/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/Users/Sites/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /Users/Sites/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

And I check this topic is created by the emit('dead_letter', {...}) from the publisher

**Comment by ccoeurderoy** [comment]
Hey @Bamorem, according to the [Google Cloud documentation](https://cloud.google.com/pubsub/docs/handling-failures#grant_forwarding_permissions), you must assign a new role to the pubsub default service account. 

Unfortunately, algoan/pubsub lib does not handle service accounts and google IAM. You must configure it by yourself! We may add a section on the README file to specify this! 

Thank you for your feedback 🙂

**Comment by Bamorem** [comment]
Hey @ccoeurderoy , well you actually can do it.
the code is simple (for each subscription, on the create callback):
` const pubsub = new PubSub();
    const subscription = pubsub.subscription(
      'my_sub',
    );
    const myPolicy = {
      bindings: [
        {
          role: 'roles/pubsub.subscriber',
          members: [
            'serviceAccount:service-XXXXXXXXXX@gcp-sa-pubsub.iam.gserviceaccount.com',
          ],
        },
      ],
    };
    await subscription.iam.setPolicy(myPolicy);`
    
    The thing is i don't see where i can have this callback . I guess you have this somewhere since it does create the subscriber somewhere
    
    do you have an idea for me to do it? or maybe you can add this code somewhere for each subscription created/updated
