### ISSUE TITLE
Wrong last rel calculation

### ISSUE THREAD

**Issue by gperdomor** [algoan/nestjs-components#66]
Hi, I have one entity with 17 rows...

When I try to filter, for example the second page, I got this headers:

`</tenants?offset=1&limit=5>; rel="first prev"; per_page="5"; page="1", </tenants?offset=4&limit=5>; rel="last"; per_page="5"; page="2", </tenants?offset=3&limit=5>; rel="next"; per_page="5"; page="3"`

The third page:
`</tenants?offset=1&limit=5>; rel="first"; per_page="5"; page="1", </tenants?offset=4&limit=5>; rel="last next"; per_page="5"; page="3", </tenants?offset=2&limit=5>; rel="prev"; per_page="5"; page="2"`

The total of pages is 4, but the last rel in headers references to page 2 and 3, which is the same page i'm trying to filter

**Comment by ccoeurderoy** [comment]
Hi @gperdomor! Thank you for your contribution, I'll have a look at your PR
