### ISSUE TITLE
How to prevent topic/subscription creation?

### ISSUE THREAD

**Issue by gitSambhal** [algoan/nestjs-components#664]
How to prevent auto creation of topic/sub for the given name? I don't want to create the topic/sub if it is not present.

**Comment by ccoeurderoy** [comment]
Hey @gitSambhal, for now the algoan/pubsub lib only supports the auto create mode. We need to adjust it in order to disable that feature! But I cannot say when

**Comment by markrity** [comment]
@ccoeurderoy so there is no way right now to use already existing subscription name ?

**Comment by gitSambhal** [comment]
> @ccoeurderoy so there is no way right now to use already existing subscription name ?
> 
> P.S. also something I don't understand , if we are having only an option to provide a prefix for a subscription name and it going to create a new subscription , how other pods of same service will not create a new subscriptions on each startup as-well ?

@markrity If the given subscription name exists then it will not be recreated.

**Comment by ccoeurderoy** [comment]
Hey @markrity, I confirm @gitSambhal's comment. When you initiate the Pub/Sub connection, it will "find or create" the subscription.

This issue is opened because today, we cannot disable the `autoCreate` mode. Disabling it will allow developers to not automatically create topics or subscriptions.

Just by curiosity @gitSambhal, do you have an example use case where you don't want to create a topic with its associated subscription? In my mind, if you declare a `@EventPattern` decorator, it should exist, right? Is it for development environments, where you just want to test one subscription?

**Comment by gitSambhal** [comment]
> Hey @markrity, I confirm @gitSambhal's comment. When you initiate the Pub/Sub connection, it will "find or create" the subscription.
> 
> This issue is opened because today, we cannot disable the `autoCreate` mode. Disabling it will allow developers to not automatically create topics or subscriptions.
> 
> Just by curiosity @gitSambhal, do you have an example use case where you don't want to create a topic with its associated subscription? In my mind, if you declare a `@EventPattern` decorator, it should exist, right? Is it for development environments, where you just want to test one subscription?

Hi @ccoeurderoy ,

My usecase is that we have one core service which publishes the message with some attributes and some handler services which subscribes to their own subscription. The subscription is already created manually along with the filters. 

During testing if I given a subscription name with spelling mistake or something else then it is created in GCP automatically and when I searched there were lot of these topic/subs automatically created which causes a confusion. 

Since we(or our devops team) create the subscription manually we don't need the auto created functionality.
Hope it helps.

**Comment by ccoeurderoy** [comment]
Hey guys, using the @algoan/pubsub v5.1.0, you can now disable the `autoCreate` mode!

```typescript
const server: GCPubSubServer = new GCPubSubServer({
      projectId: '...',
      topicsNames: [...],
      listenOptions: {
        topicOptions: {
          autoCreate: false,
        }
      }
    });
```

So if you disable the auto-create mode and enter the wrong topic/subscription name, the application will crash with a `5 NOT_FOUND: Topic not found` error! It might not be the best way to handle this, but at least it should prevent answer to this issue.

I'm closing this for now, but feel free to re-open this issue if it doesn't work 😊

**Comment by markrity** [comment]
@ccoeurderoy but it looks like you still have no way to provide a subscription name. 
I can have 1 topic with 5 subscriptions 
topic
- sub1
- sub2
- sub3
- sub4
- sub5

I want to provide service1 -> sub1 , service2 -> sub2 .

So having autoCreate off, not covering this usecase right ?

**Comment by ccoeurderoy** [comment]
Yes unfortunately that's right. For now, the subscription name is attached to a single topic which is a shame for a Pub/Sub pattern.

I will create another issue in order to not forget this use case!

**Comment by gitSambhal** [comment]
Hi @ccoeurderoy,
I got one issue, I am using this package for pubsub microservice and I want to listen for events(subscriptions) using `EventPattern` but this package is considering that subscription name as the topic name and tries to create it. Since I have added `autoCreate` as `false`,  it throws `5 NOT_FOUND: Topic not found` error. My subscription is created in another topic so until I create a topic named exactly as the subscription name it doesn't work. When I remove the autoCreate flag then it creates the topic only without any subscription name and my subscription starts to work.
Any help on this will be much appreciated.
Thanks

**Comment by ccoeurderoy** [comment]
Yes this is related to @markrity's issue, so I've created a new issue to solve this problem (#714)! I am considering using `extras` from the `EventPattern` decorator to specify a topic for a given subscription

**Comment by ccoeurderoy** [comment]
@gitSambhal it should be resolved in the latest version of @algoan/nestjs-google-pubsub-microservice and @algoan/pubsub!

**Comment by gitSambhal** [comment]
> it should be resolved in the latest version

Thank you @ccoeurderoy 
Will try it out.

**Comment by gitSambhal** [comment]
Hi @ccoeurderoy,

Thanks for this update,  today I upgraded these packages  and my issue is resolved now but I found one issue that I can give any topic name and it will just work without throwing error. I am not sure if it is expected or a bug. 
I had assumed that it will throw the error in this case if the subscription doesn't belong to the topic or if the topic doesn't exist.

**Comment by gitSambhal** [comment]
Hi @ccoeurderoy 
Again I tested an found that when the topic or subscription name is not available then it throws the error but there is no error when topic and sub  is created but the sub doesn't belong to the topic.

**Comment by ccoeurderoy** [comment]
Hey @gitSambhal, indeed there is no error. For consistency, I've released a fix on [algoan/pubsub](https://github.com/algoan/pubsub/releases/tag/v5.2.1)

**Comment by gitSambhal** [comment]
Thank you @ccoeurderoy
