### ISSUE TITLE
[IMP] Ability to provide subscriptions with topics

### ISSUE THREAD

**Issue by ccoeurderoy** [algoan/nestjs-components#714]
> Yes unfortunately that's right. For now, the subscription name is attached to a single topic which is a shame for a Pub/Sub pattern.
> I will create another issue in order to not forget this use case!

_Originally posted by @ccoeurderoy in https://github.com/algoan/nestjs-components/issues/664#issuecomment-1543649102_

### Description

Add an option letting developers choose their subscription and topics

**Comment by markrity** [comment]
Thank you 👑

**Comment by ccoeurderoy** [comment]
Should be done in the v3.1.0! Don't forget to upgrade @algoan/pubsub to v5.2.0 🙂 Let me know if it works for you!

**Comment by markrity** [comment]
Thank you for this :) Can be really useful
