### ISSUE TITLE
Upgrade peer dependencies from @nestjs/core@">8.x.x" to @nestjs/core@">8"

### ISSUE THREAD

**Issue by anthony-langford** [algoan/nestjs-components#772]
Hello, I'm attempting to upgrade my NestJS project from version 8 to version 10 and am blocked by `@algoan/nestjs-google-pubsub-client` requiring a peer dependency of `@nestjs/core@">8.x.x"`. Could this be updated to `@nestjs/core@">8"`?

**Comment by anthony-langford** [comment]
Is this library maintained?

**Comment by g-ongenae** [comment]
Hello @anthony-langford, yes, it is still maintained, although, it has changed maintainers.
This change and other updates have been scheduled to be done before the end of this month.
Thank you for your understanding.

**Comment by g-ongenae** [comment]
Hello @anthony-langford, after verification, we use it, here at @algoan, with nestjs peer dependencies at version 9 on one of our services (with @algoan/nestjs-google-pubsub-client": at v0.4.8 and @algoan/nestjs-google-pubsub-microservice at v3.0.3) and we don't have the error during the installation of node_modules.

Also, as I stated in [the discussion of my PR](https://github.com/algoan/nestjs-components/pull/782#issuecomment-1779543868), this requirement should be satisfied with v9 or v10 of nestjs peer dependencies based on [npmjs semver validation](https://semver.npmjs.com/).

I will still merge and publish this PR as it seems clearer to me as only `>= 8`, however I think if the problem remains we need to look elsewhere.
