### ISSUE TITLE
[CLASS_VALIDATORS] Allow to give fallback value to enum validator

### ISSUE THREAD

**Issue by amarlankri** [algoan/nestjs-components#833]
# Description
Currently, it is possible to check that the value of a property is included in an enum definition using `isEnum` validator. Its behaviour is the following:
- If the value is one of the literal value of the enum, then the object is validated
- Otherwise, throw an error

Most of the time, this behaviour is desired but it may be too strict in other use cases. For those cases, having the ability to provide a fallback value seems to be a good solution. The behaviour would be:
- If the value is one of the literal value of the enum, then the object is validated
- Otherwise, return a default value of the enum

# Solution proposed
Creating a new validator `IsEnumWithFallback` which allows to provide a fallback function in addition to the enum type. Here is an example of its usage:
```ts
export enum UserRole {
  ADMIN = 'ADMIN',
  READER = 'READER',
}

class UserDto {
  @IsEnumWithFallback({
    type: UserRole,
    fallback: (value: UserRole) => UserRole.READER // if the role is not "ADMIN" or "READER", then the role will be "READER". 
  })
  public role?: UserRole;
}
```

This solution seems to be possible according to [class validators documentation](https://github.com/typestack/class-validator?tab=readme-ov-file#custom-validation-decorators).

# FAQs
- **Why not providing a fallback function rather than just a value?**
Even if the validator will not throw an error if the enum value is wrong, the fallback should not be considered as the "normal" use case - that's why it is named `fallback` rather than `default`. As a result, as a developper, you will probably want to add logs when the fallback is called. By the way, having a function allow more complex logic if needed.
- **Why not overloading the existing `isEnum` validator?**
I just thought it was better to distinguish clearly the two validators but I don't have real strong arguments. If you think it is better, I am open to it (however, I will have to check the feasibility of the solution).

**Comment by qhdinh** [comment]
In my opinion, a validator is supposed to only return validated or not. If you would like to return different values based on where the object is validated or not, it won't be a validator anymore. Your proposed feature seems more like a transformer to me.
So I think it'd be better to use `@Transform` of class-transformer. 
https://github.com/typestack/class-transformer#additional-data-transformation
And in that decorator, we use function `isEnum()` to determine if the object value belongs to enum or not and return corresponding result value.

**Comment by amarlankri** [comment]
The solution described in #834 has been chosen.
